geschke_admin_translator_gui_homepage:
    path:     /
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:index }

geschke_admin_translator_gui_bundles:
    path:     /bundles/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:listBundles }


geschke_admin_translator_gui_language_add:
    path:     /language-add/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:addLanguage }
