geschke_admin_translator_gui_homepage:
    path:     /
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:index }

geschke_admin_translator_gui_bundles:
    path:     /bundles/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:listBundles }


geschke_admin_translator_gui_language_add:
    path:     /language-add/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:addLanguage }

geschke_admin_translator_gui_language_edit:
    path:     /language-edit/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Language:listTranslations }


geschke_admin_translator_gui_language_rescan:
    path:     /language-rescan/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Language:rescanTranslations }
