geschke_admin_translator_gui_homepage:
    path:     /
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:index }

geschke_admin_translator_gui_bundles:
    path:     /bundles/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Bundle:listBundles }


geschke_admin_translator_gui_language_add:
    path:     /language-add/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:addLanguage }


geschke_admin_translator_gui_language_delete:
    path:     /language-delete/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Default:deleteLanguage }



geschke_admin_translator_gui_language_copy:
    path:     /language-copy/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Language:processCopy }


geschke_admin_translator_gui_language_rescan:
    path:     /language-rescan/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Language:rescanTranslations }

geschke_admin_translator_gui_language_messageref:
    path:     /language-messageref/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Language:messageReference }
    methods:  [GET]


geschke_admin_translator_gui_language_edit:
    path:     /language-edit/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Translation:listTranslations }


geschke_admin_translator_gui_translation:
    path:     /language-translate/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Translation:translate }
    methods:  [GET]

geschke_admin_translator_gui_translation_process:
    path:     /language-translate/
    defaults: { _controller: GeschkeAdminTranslatorGUIBundle:Translation:processTranslate }
    methods:  [POST]

