#services:
#    geschke_admin_translator_gui.example:
#        class: Geschke\Bundle\Admin\TranslatorGUIBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    geschke_bundle_admin_translatorguibundle.locale_messages.class: Geschke\Bundle\Admin\TranslatorGUIBundle\Util\LocaleMessages

services:
    geschke_bundle_admin_translatorguibundle.locale_messages:
        class:   "%geschke_bundle_admin_translatorguibundle.locale_messages.class%"
        arguments: [@kernel]

    geschke_bundle_admin_translatorguibundle.twig.extension:
        class: Geschke\Bundle\Admin\TranslatorGUIBundle\Extension\TwigExtension
        tags:
            - { name: twig.extension }
