Geschke\Bundle\Admin\TranslatorGUIBundle\Entity\LanguageFile:
    properties:
        bundle:
            - NotBlank: ~
        locale:
            - NotBlank: ~
    getters:
        languageChosen:
            - "True": { message: "Please choose locale or enter locale string." }

