Geschke\Bundle\Admin\TranslatorGUIBundle\Entity\LanguageFile:
    properties:
        bundle:
            - NotBlank: ~
        locale:
            - NotBlank: ~
    getters:
        languageChosen:
            - "True": { message: "message.validator_language_invalid_choose_locale" }

# Please choose locale or enter locale string.
